### PR TITLE
`Collection` module

### PR DESCRIPTION
**Pull request by kimburgess**
Provides a common interface and abstract tooling for working with any types that model a [binary relation](https://en.wikipedia.org/wiki/Binary_relation).

The intent of this mixin is to provide functionality similar to the Indexable module from std-lib, but generalised for both index and key based collections.

### CODE REVIEW

**Comment by kimburgess** [comment]
Open to alternative naming suggestions to `Relatable` too.

**Comment by stakach** [comment]
Relatable does sound like a good name for an ORM, so my only concern is that it's too good a name

**Comment by kimburgess** [comment]
Other options I'd considered:
1. `Map` (although again, highly prone to a name conflict)
2. `Associative`
With both of these though, the type is not technically a map / associative array as this module has nothing to do with adding, deleting or mutating values so weary that these may both cause confusion.

**Comment by kimburgess** [comment]
Up and running with recursive types! I've hit a few impasses with the current compiler functionality, but noted where this is the case so that it can be revisited as things mature. External API will remain unchanged when this happens.

**Comment by kimburgess** [comment]
After sleeping on it, a possibly clearer name could just be `Collection`. Doesn't conflict with std-lib, is pretty clear on the intent and fits the types this would be used in.

**Comment by kimburgess** [comment]
Cool, this should be fairly static now. Apologies for the smattering of commits after the review request @stakach and @caspiano. When you get a chance feedback, comments, questions and abuse welcomed.

**Review by caspiano — COMMENTED** [review]
LGTM. The traverse for JSON::Any is tantalising.

**Pull request merged**
